### ISSUE TITLE
Images are glitchy

### ISSUE THREAD

**Issue by KweezyCode** [Troplo/office-install.sh#5]
![image](https://github.com/Troplo/office-install.sh/assets/36813920/7cdb334e-da2b-4053-95aa-12070abf07eb)
Manjaro Latest (KDE 6)
CPU: AMD Ryzen 7 5700G with Radeon Graphics
GPU: Radeon Graphics

**Comment by Troplo** [comment]
I believe it has something to do with the wineprefix's DPI font scale, I added an option to easily open winecfg in the prefixes, if you set the DPI to 96 in the Graphics tab, does it fix it? (the UI scale will of course be smaller, I have a 4k monitor which is why it was preconfigured to that, but it probably should just be 96 by default.)

**Comment by KweezyCode** [comment]
yea, looks better but too small on my screen
